### PR TITLE
Fix handling split transactions for category chart

### LINKED ISSUE #143: Split transactions with multiple categories count as a single category for monthly totals
For instance, if I have a split transaction of £10 for category A and £90 for category B it may show up as £100 for category A and £0 for category B on the dashboard chart.

### PR DESCRIPTION
**Pull request by avee87**
Counting splits separately so they correctly update each category

This should fix #143

### CODE REVIEW

File: front/stores/appStore.js [hunk 1]
```diff
@@ -1,16 +1,9 @@
...
-import DateUtils from '~/utils/DateUtils'
-import { FORM_CONSTANTS_TRANSACTION_FIELDS_LIST } from '~/constants/FormConstants'
+import { useLocalStorage } from '@vueuse/core'
 import ResponseUtils from '~/utils/ResponseUtils'
 import { compareVersionStrings } from '~/utils/DataUtils'
 import InfoRepository from '~/repository/InfoRepository.js'
 import { get } from 'lodash'
-import { HERO_ICONS, HERO_ICONS_LIST } from '~/constants/TransactionConstants.js'
-import { NUMBER_FORMAT } from '~/utils/MathUtils.js'
-import ProfileRepository from '~/repository/ProfileRepository'
```
Comment (avee87) [inline front/stores/appStore.js:12]: There is something very wrong with imports. Without deleting this line Pico wouldn't load for me saying "Cannot access 'BaseRepository' before initialization". Same happens if I remove some of the unused imports in other files...
